<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AzureFunctionsVersion>v4</AzureFunctionsVersion>
		<OutputType>Exe</OutputType>
		<RootNamespace>Defra.Trade.Events.IDCOMS.GCEnricher</RootNamespace>
		<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
	</PropertyGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="Azure.Identity" Version="1.17.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.52.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.5" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.22.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.0.2" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.OpenApi" Version="1.6.0" />
		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi.Core" Version="1.6.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="2.50.0" />
		<PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.23.0" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
		<PackageReference Include="Polly.Caching.Memory" Version="3.0.2" />
		<PackageReference Include="NJsonSchema" Version="11.0.2" />
		<PackageReference Include="Defra.Trade.Common.Logging" Version="3.0.1" />
		<PackageReference Include="Defra.Trade.Common.Functions.Isolated" Version="2.0.0" />
		<PackageReference Include="Defra.Trade.Common.Function.Health" Version="4.1.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Defra.Trade.Events.IDCOMS.GCEnricher.Application\Defra.Trade.Events.IDCOMS.GCEnricher.Application.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="host.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="local.settings.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</None>
	</ItemGroup>
</Project>
