<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>

	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="15.1.3" />
		<PackageReference Include="Defra.Trade.Common.Functions.Isolated" Version="2.0.0" />
		<PackageReference Include="Defra.Trade.Common" Version="5.0.2" />
		<PackageReference Include="Defra.Trade.Common.Security" Version="4.0.3" />
	</ItemGroup>
</Project>
